name: terraform destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        default: 'dev'
      target:
        description: 'Target to destroy'   #target to destroy
        required: true
        type: choice
        options:
          - buckets
          - cloud_run
          - all
jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }} #manual approval
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Terraform Init
        working-directory: ./infra
        run: terraform init \
          -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
          -backend-config="prefix=${{ github.event.inputs.environment }}/terraform"
      - name: Terraform Destroy
        working-directory: ./infra
        run: |
          if [ "${{ github.event.inputs.target }}" == "buckets" ]; then
            terraform destroy \
              -target=google_storage_bucket.my_bucket \
              -var="project_id=${{ vars.GCP_PROJECT_ID }}" \
              -var="region=${{ vars.GCP_REGION }}" \
              -var="environment=${{ github.event.inputs.environment }}" \
              -auto-approve
          elif [ "${{ github.event.inputs.target }}" == "cloud_run" ]; then
            terraform destroy \
              -target=google_cloud_run_v2_service.default \
              -var="project_id=${{ vars.GCP_PROJECT_ID }}" \
              -var="region=${{ vars.GCP_REGION }}" \
              -var="environment=${{ github.event.inputs.environment }}" \
              -auto-approve
          else
            terraform destroy \
              -var="project_id=${{ vars.GCP_PROJECT_ID }}" \
              -var="region=${{ vars.GCP_REGION }}" \
              -var="environment=${{ github.event.inputs.environment }}" \
              -auto-approve
          fi