name: Terraform Apply
on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy to'
          required: true
          default: 'development'
        plan_run_number:
          description: 'Run number of the plan to apply (from terraform-plan workflow)'
          required: true
          type: string
permissions:
  contents: read
  id-token: write
  security-events: write
jobs:
    apply:
      runs-on: ubuntu-latest
      environment: ${{ github.event.inputs.environment }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
        - name: Authenticate to Google Cloud
          uses: google-github-actions/auth@v2
          with:
            workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_01 }}
        - name: Set up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
        - name: download the plan artifacts
          uses: dawidd6/action-download-artifact@v3
          with:
            workflow: terraform-plan.yml
            run_number: ${{ github.event.inputs.plan_run_number }}
            name: tfplan-${{ github.event.inputs.environment }}-${{ github.event.inputs.plan_run_number }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
        - name: Initialize Terraform 
          run: terraform init -backend-config="bucket=${{ secrets.GCP_TF_STATE_BUCKET }}" -backend-config="prefix=terraform/state/dev"
          working-directory: ./
        - name: Terraform Apply
          id: apply
          run: |
            terraform apply \
              -auto-approve \
              -input=false \
              tfplanc.binary
          working-directory: ./
            
        
          